[package]
name = "caldav-derive"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.26"
quote = "1.0"

[dependencies.syn]
version = "1.0"
features = ["extra-traits"]
